# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Running lint and tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox-environments: [flake8, pytest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run ${{ matrix.tox-environment }}
      run: tox -e ${{ matrix.tox-environment }}
